export const teams = [
    {
        name: "Gavilanes",
        secret: "12345",
        players: [
            {
                name: "Andres",
                games: 5,
                singles: 10,
                doubles: 5,
                triples: 2,
                homeruns: 1,
                sbs: 3,
                walks: 5,
                rbis: 10,
                outs: 5,
                strikeouts: 2,
            },
            {
                name: "Daniel",
                games: 5,
                singles: 55,
                doubles: 20,
                triples: 5,
                homeruns: 20,
                sbs: 3,
                walks: 5,
                rbis: 10,
                outs: 250,
                strikeouts: 50,
            },
            {
                name: "Rogelio",
                games: 5,
                singles: 10,
                doubles: 5,
                triples: 2,
                homeruns: 1,
                sbs: 3,
                walks: 5,
                rbis: 10,
                outs: 5,
                strikeouts: 2,
            },
            {
                name: "Diego",
                games: 5,
                singles: 55,
                doubles: 20,
                triples: 5,
                homeruns: 20,
                sbs: 3,
                walks: 5,
                rbis: 10,
                outs: 250,
                strikeouts: 50,
            },
            {
                name: "Esteban",
                games: 5,
                singles: 10,
                doubles: 5,
                triples: 2,
                homeruns: 1,
                sbs: 3,
                walks: 5,
                rbis: 10,
                outs: 5,
                strikeouts: 2,
            },
            {
                name: "Gabriel",
                games: 5,
                singles: 55,
                doubles: 20,
                triples: 5,
                homeruns: 20,
                sbs: 3,
                walks: 5,
                rbis: 10,
                outs: 250,
                strikeouts: 50,
            },
            {
                name: "Jose",
                games: 5,
                singles: 10,
                doubles: 5,
                triples: 2,
                homeruns: 1,
                sbs: 3,
                walks: 5,
                rbis: 10,
                outs: 5,
                strikeouts: 2,
            },
            {
                name: "Emilio",
                games: 5,
                singles: 55,
                doubles: 20,
                triples: 5,
                homeruns: 20,
                sbs: 3,
                walks: 5,
                rbis: 10,
                outs: 250,
                strikeouts: 50,
            },
            {
                name: "Juan",
                games: 5,
                singles: 10,
                doubles: 5,
                triples: 2,
                homeruns: 1,
                sbs: 3,
                walks: 5,
                rbis: 10,
                outs: 5,
                strikeouts: 2,
            },
            {
                name: "Pedro",
                games: 5,
                singles: 55,
                doubles: 20,
                triples: 5,
                homeruns: 20,
                sbs: 3,
                walks: 5,
                rbis: 10,
                outs: 250,
                strikeouts: 50,
            },
        ]
    },
    {
        name: "Panteras",
        secret: "12345",
        players: [
            {
                name: "Alonso",
                singles: 0,
                doubles: 0,
                triples: 0,
                homeruns: 0,
            },
            {
                name: "Miguel",
                singles: 0,
                doubles: 0,
                triples: 0,
                homeruns: 0,
            },
            {
                name: "Tato",
                singles: 0,
                doubles: 0,
                triples: 0,
                homeruns: 0,
            },
            {
                name: "Andres",
                singles: 0,
                doubles: 0,
                triples: 0,
                homeruns: 0,
            },
            {
                name: "Santiago",
                singles: 0,
                doubles: 0,
                triples: 0,
                homeruns: 0,
            },
            {
                name: "Alexander",
                singles: 0,
                doubles: 0,
                triples: 0,
                homeruns: 0,
            },
            {
                name: "Nacho",
                singles: 0,
                doubles: 0,
                triples: 0,
                homeruns: 0,
            },
            {
                name: "Diego",
                singles: 0,
                doubles: 0,
                triples: 0,
                homeruns: 0,
            },
            {
                name: "Gabriel",
                singles: 0,
                doubles: 0,
                triples: 0,
                homeruns: 0,
            },
            {
                name: "Lorenzo",
                singles: 0,
                doubles: 0,
                triples: 0,
                homeruns: 0,
            },
        ]
    }
]