export const Gavilanes = {
    name: "Gavilanes",
    secret: "12345",
    players: [
        {
            name: "Alonso",
            singles: 0,
            doubles: 0,
            triples: 0,
            homeruns: 0,
        },
        {
            name: "Miguel",
            singles: 0,
            doubles: 0,
            triples: 0,
            homeruns: 0,
        },
        {
            name: "Tato",
            singles: 0,
            doubles: 0,
            triples: 0,
            homeruns: 0,
        },
        {
            name: "Andres",
            singles: 0,
            doubles: 0,
            triples: 0,
            homeruns: 0,
        },
        {
            name: "Santiago",
            singles: 0,
            doubles: 0,
            triples: 0,
            homeruns: 0,
        },
        {
            name: "Alexander",
            singles: 0,
            doubles: 0,
            triples: 0,
            homeruns: 0,
        },
        {
            name: "Nacho",
            singles: 0,
            doubles: 0,
            triples: 0,
            homeruns: 0,
        },
        {
            name: "Diego",
            singles: 0,
            doubles: 0,
            triples: 0,
            homeruns: 0,
        },
        {
            name: "Gabriel",
            singles: 0,
            doubles: 0,
            triples: 0,
            homeruns: 0,
        },
        {
            name: "Lorenzo",
            singles: 0,
            doubles: 0,
            triples: 0,
            homeruns: 0,
        },
    ]
}